"""Test dlt upsert pipeline: update rows spread across multiple Iceberg data files.

Reads parquet files from /app/parquet_updates/ (generated by generate_updates.py)
and runs a merge/upsert into the existing Iceberg table created by the initial load.

Run inside the dlt-loader container:
    python /app/test-upsert-docker.py
"""

import gc
import os
import resource
import time
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

os.environ["RUNTIME__LOG_LEVEL"] = "INFO"
import dlt

PARQUET_DIR = Path("/app/parquet_updates")
BATCH_SIZE = int(os.environ.get("BATCH_SIZE", "1_000"))


def get_memory_mb() -> float:
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024


def log_memory(label: str) -> None:
    print(
        f"  [{label}] RSS: {get_memory_mb():.0f} MB"
        f" | Arrow pool: {pa.total_allocated_bytes() / 1024**2:.0f} MB",
        flush=True,
    )


def parquet_resource(parquet_dir: str, batch_size: int = 1_000):
    """Yield batches from update parquet files one at a time."""
    parquet_files = sorted(Path(parquet_dir).glob("*.parquet"))
    n_files = len(parquet_files)
    total_mb = sum(f.stat().st_size for f in parquet_files) / (1024**2)
    print(
        f"[extract] Loading {n_files} update files ({total_mb:.1f} MB) from {parquet_dir}",
        flush=True,
    )

    total_rows = 0
    for file_idx, pf_path in enumerate(parquet_files):
        file_mb = pf_path.stat().st_size / (1024**2)
        print(
            f"[extract] File {file_idx + 1}/{n_files}: {pf_path.name} ({file_mb:.1f} MB)",
            flush=True,
        )

        pf = pq.ParquetFile(str(pf_path))
        file_rows = 0
        for batch in pf.iter_batches(batch_size=batch_size):
            file_rows += batch.num_rows
            total_rows += batch.num_rows
            yield batch

        del pf
        gc.collect()
        print(
            f"  [extract] Done file {file_idx + 1}: {file_rows:,} rows"
            f" | total: {total_rows:,} | RSS {get_memory_mb():.0f} MB",
            flush=True,
        )

    print(f"[extract] Finished: {total_rows:,} rows from {n_files} files", flush=True)


def main():
    if not PARQUET_DIR.exists() or not list(PARQUET_DIR.glob("*.parquet")):
        print(f"No update parquet files found at {PARQUET_DIR}")
        print("Run generate_updates.py first.")
        return

    pipeline = dlt.pipeline(
        pipeline_name="large_parquet_docker",
        destination=dlt.destinations.filesystem(
            bucket_url=os.environ.get("BUCKET_URL", "s3://warehouse/my-lake"),
            credentials={
                "aws_access_key_id": os.environ.get("AWS_ACCESS_KEY_ID", "admin"),
                "aws_secret_access_key": os.environ.get("AWS_SECRET_ACCESS_KEY", "password"),
                "endpoint_url": os.environ.get("AWS_ENDPOINT_URL_S3", "http://minio:9000"),
                "region_name": os.environ.get("AWS_REGION", "us-east-1"),
            },
        ),
        dataset_name="large_test",
    )

    resource_ = dlt.resource(
        parquet_resource(str(PARQUET_DIR), batch_size=BATCH_SIZE),
        name="wide_table",
        table_format="iceberg",
        write_disposition="merge",
        primary_key="id",
    )

    print(f"\nStarting UPSERT pipeline (batch_size={BATCH_SIZE})...", flush=True)
    log_memory("before pipeline.run")

    t_start = time.monotonic()
    try:
        info = pipeline.run(resource_)
        elapsed = time.monotonic() - t_start
        print(f"\n=== Load Info ({elapsed:.1f}s total) ===", flush=True)
        print(info, flush=True)
    except Exception as e:
        elapsed = time.monotonic() - t_start
        print(f"\n=== FAILED after {elapsed:.1f}s ===", flush=True)
        print(f"Error: {e}", flush=True)
        import traceback

        traceback.print_exc()
    finally:
        log_memory("after pipeline.run")
        print(f"\n=== Peak Memory ===", flush=True)
        print(f"  Peak RSS: {get_memory_mb():.0f} MB", flush=True)


if __name__ == "__main__":
    main()
